//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PJ64.rc
//
#define MAIN_MENU                       116
#define IDD_Settings_PlugSel            121
#define IDR_WINDOWMODE                  122
#define IDD_TLB                         123
#define IDD_Logging_Registers           125
#define IDD_Logging_PifRam              126
#define IDD_Logging_General             127
#define IDD_About                       128
#define IDB_PJ64LOGO                    130
#define IDD_Settings_Directory          131
#define IDD_Settings_Options            132
#define IDD_Settings_Rom                133
#define IDD_MANAGECHEATS                134
#define IDD_Cheats_List                 135
#define IDD_Cheats_CodeEx               136
#define IDD_Cheats_Range                137
#define IDD_Cheats_Add                  138
#define IDD_Settings_ShellInt           139
#define IDR_ROMBROWSER                  140
#define IDD_Settings_RomBrowser         140
#define IDR_CPURUNNING                  141
#define IDD_About_Ini                   143
#define IDD_Settings_General            144
#define IDD_Settings_RomNotes           145
#define IDI_RIGHT                       151
#define IDI_LEFT                        153
#define IDR_POPUP                       155
#define IDD_Cheats_Main                 159
#define IDR_CHEAT_MENU                  160
#define IDD_Cheats_Edit                 160
#define IDD_LangSelect                  161
#define IDB_AboutTxt                    166
#define IDB_BITMAP1                     167
#define IDR_ABOUT_TXT                   177
#define IDD_Debugger_MemDump            178
#define IDB_BITMAP2                     182
#define IDB_BITMAP3                     183
#define IDD_MEM_BOOKMARK_EDIT           184
#define IDC_CLOSE_BUTTON                1001
#define RSP_LIST                        1004
#define RSP_ABOUT                       1006
#define IDC_INFO_FILENAME               1007
#define IDC_INFO_ROMNAME                1008
#define IDC_INFO_CARTID                 1009
#define IDC_INFO_ROMSIZE                1010
#define IDC_INFO_CIC                    1011
#define IDC_INFO_MANUFACTURER           1012
#define IDC_LIST                        1012
#define IDC_INFO_COUNTRY                1013
#define IDC_TLB_ENTRIES                 1013
#define IDC_INFO_CRC1                   1014
#define IDC_TLB_RULES                   1014
#define IDC_INFO_CRC2                   1015
#define IDC_LIST2                       1015
#define GFX_LIST                        1016
#define IDC_INFO_VERSION                1016
#define IDC_INFO_SDK                    1017
#define GFX_ABOUT                       1019
#define IDC_ADDR_EDIT                   1024
#define AUDIO_LIST                      1028
#define AUDIO_ABOUT                     1031
#define CONT_LIST                       1032
#define CONT_ABOUT                      1035
#define IDC_CP0_WRITE                   1036
#define IDC_CP0_READ                    1037
#define IDC_CACHE                       1038
#define IDC_EXCEPTIONS                  1039
#define IDC_INTERRUPTS                  1040
#define IDC_TLB                         1041
#define IDC_ROM_HEADER                  1042
#define IDC_UNKOWN                      1043
#define IDC_RI_REG                      1044
#define IDC_UNKOWN2                     1044
#define IDC_SI_REG                      1045
#define IDC_RDRAM                       1046
#define IDC_SP_REG                      1047
#define IDC_DPC_REG                     1048
#define IDC_DPS_REG                     1049
#define IDC_MI_REG                      1050
#define IDC_VI_REG                      1051
#define IDC_AI_REG                      1052
#define IDC_MOD_CODE2                   1053
#define IDC_PI_REG                      1053
#define IDC_SI_DMA                      1054
#define IDC_DIRECT_WRITE                1055
#define IDC_DMA_WRITE                   1056
#define IDC_DIRECT_READ                 1057
#define IDC_DMA_READ                    1058
#define IDC_CONT_PAK                    1059
#define IDC_ROM_OTHER                   1062
#define IDC_ROM_DIR                     1063
#define IDC_ROM_DEFAULT                 1064
#define IDC_SELECT_ROM_DIR              1065
#define IDC_PLUGIN_OTHER                1066
#define IDC_PLUGIN_DIR                  1067
#define IDC_PLUGIN_DEFAULT              1068
#define IDC_SELECT_PLUGIN_DIR           1069
#define IDC_UP                          1069
#define IDC_AUTO_OTHER                  1070
#define IDC_DOWN                        1070
#define IDC_AUTO_DIR                    1071
#define IDC_AUTO_DEFAULT                1072
#define IDC_SELECT_AUTO_DIR             1073
#define IDC_INSTANT_OTHER               1074
#define IDC_INSTANT_DIR                 1075
#define IDC_INSTANT_DEFAULT             1076
#define IDC_SELECT_INSTANT_DIR          1077
#define IDC_SNAP_OTHER                  1078
#define IDC_SNAP_DIR                    1079
#define IDC_SNAP_DEFAULT                1080
#define IDC_SELECT_SNAP_DIR             1081
#define IDC_START_ON_ROM_OPEN           1084
#define IDC_USE_TLB                     1084
#define IDC_SELFMOD                     1085
#define IDC_BLOCK_LINKING               1086
#define IDC_RDRAM_SIZE                  1087
#define IDC_CPU_TYPE                    1088
#define IDC_SAVE_TYPE                   1089
#define IDC_MEMORY_SIZE_TEXT            1090
#define IDC_ABL                         1090
#define IDC_USEINI                      1091
#define IDC_SAVE_TYPE_TEXT              1091
#define IDC_CPU_TYPE_TEXT               1092
#define IDC_ZIP                         1092
#define IDC_SELFMOD_TEXT                1093
#define IDC_BLOCK_LINKING_TEXT          1094
#define IDC_REMEMBER                    1095
#define IDC_COUNTFACT_TEXT              1095
#define IDC_AUTOSLEEP                   1096
#define IDC_COUNTFACT                   1096
#define IDC_RSP_NAME                    1097
#define IDC_REMEMBERDIR                 1097
#define IDC_LARGE_COMPILE_BUFFER        1097
#define IDC_GFX_NAME                    1098
#define IDC_ROM_REGCACHE                1098
#define IDC_AUDIO_NAME                  1099
#define IDC_DELAY_SI                    1099
#define IDC_CONT_NAME                   1100
#define IDC_ROM_SPHACK                  1100
#define IDC_DIR_FRAME1                  1101
#define IDC_AUDIO_SIGNAL                1101
#define IDC_DIR_FRAME2                  1102
#define IDC_DIR_FRAME3                  1103
#define IDC_DIR_FRAME4                  1104
#define IDC_DIR_FRAME5                  1105
#define IDC_INFO                        1106
#define IDC_TEXT2                       1107
#define IDC_TEXT3                       1108
#define IDC_TEXT4                       1109
#define IDC_TEXT5                       1110
#define IDC_ROMSEL_TEXT1                1111
#define IDC_ROMSEL_TEXT2                1112
#define IDC_ROMSEL_TEXT3                1113
#define IDC_ROMSEL_TEXT4                1114
#define IDC_DELETE                      1118
#define IDC_UNMARK                      1119
#define IDC_NOTES                       1120
#define IDC_CHEAT_LIST                  1121
#define IDC_CHEAT_NAME                  1122
#define IDC_CHEAT_FULL                  1123
#define IDC_VALUE                       1124
#define IDC_RANGE                       1125
#define IDC_ADD                         1126
#define IDC_INSERT                      1127
#define IDC_CLEAR                       1128
#define IDC_MOD_CODE                    1129
#define IDC_CODE_NAME                   1130
#define IDC_USE_ROMBROWSER              1133
#define IDC_USING                       1134
#define IDC_AVALIABLE                   1135
#define IDC_REMOVE                      1137
#define IDC_RECURSION                   1138
#define IDC_V64                         1141
#define IDC_Z64                         1142
#define IDC_LOAD_FULLSCREEN             1142
#define IDC_N64                         1143
#define IDC_ROMSEL_TEXT5                1143
#define IDC_REMEMBER_CHEAT              1143
#define IDC_ROM                         1144
#define IDC_ROMSEL_TEXT6                1144
#define IDC_BASIC_MODE                  1144
#define IDC_JAP                         1145
#define IDC_PAL                         1146
#define IDC_USA                         1147
#define IDC_SHELL_INT_TEXT              1149
#define IDC_RDB_HOME                    1150
#define IDC_CHT_HOME                    1151
#define IDC_RDX_HOME                    1152
#define IDC_LAN                         1154
#define IDC_LAN_AUTHOR                  1155
#define IDC_LAN_VERSION                 1156
#define IDC_LAN_DATE                    1157
#define IDC_RDB                         1158
#define IDC_RDB_AUTHOR                  1159
#define IDC_RDB_VERSION                 1160
#define IDC_RDB_DATE                    1161
#define IDC_CHT                         1162
#define IDC_CHT_AUTHOR                  1163
#define IDC_CHT_VERSION                 1164
#define IDC_CHT_DATE                    1165
#define IDC_RDX                         1166
#define IDC_RDX_AUTHOR                  1167
#define IDC_RDX_VERSION                 1168
#define IDC_RDX_DATE                    1169
#define IDC_NEWCHEAT                    1172
#define IDC_INFO_LOCATION               1178
#define IDC_CHEAT_CODES                 1178
#define IDC_STATE                       1179
#define IDC_CHEATSFRAME                 1188
#define IDC_ADDCHEATSFRAME              1189
#define IDC_CORE_DEFAULTS               1190
#define IDC_CHEAT_OPTIONS               1190
#define IDC_ROM_NAME                    1191
#define IDC_LABEL_OPTIONS               1191
#define IDC_FILE_NAME                   1192
#define IDC_LABEL_OPTIONS_FORMAT        1192
#define IDC_LOCATION                    1193
#define IDC_ROM_SIZE                    1194
#define IDC_CART_ID                     1195
#define IDC_MANUFACTURER                1196
#define IDC_COUNTRY                     1197
#define IDC_CRC1                        1198
#define IDC_CRC2                        1199
#define IDC_CIC_CHIP                    1200
#define IDC_NOTESFRAME                  1201
#define IDC_VERSION                     1201
#define IDC_SDK                         1202
#define IDC_NOTE                        1205
#define IDC_DIGITAL_TEXT                1206
#define IDC_VALUE_TEXT                  1207
#define IDC_NOTES_TEXT                  1208
#define IDC_STATUS_TEXT                 1209
#define IDC_STATUS                      1210
#define IDC_CORE_NOTES                  1211
#define IDC_PLUGIN_NOTE                 1212
#define IDC_CORE                        1213
#define IDC_PLUGIN                      1214
#define IDC_NAME                        1215
#define IDC_CODE                        1216
#define IDC_CHEATNOTES                  1217
#define IDC_CODE_DES                    1218
#define IDC_LANG_SEL                    1219
#define IDC_EMULATE_AI                  1240
#define IDC_ABOUT_VER                   1240
#define IDC_ABOUT_SCROLL                1244
#define IDC_MD_RANGE                    1245
#define IDC_MD_RANGESTART               1246
#define IDC_MD_RANGEEND                 1247
#define IDC_COMBO2                      1248
#define IDC_MD_FORMAT                   1248
#define IDC_BUTTON1                     1249
#define IDC_Close                       1249
#define IDC_VIS_RESET                   1249
#define IDC_COMMAND1                    1250
#define IDC_VIS                         1251
#define IDC_GENSET_TEXT                 1252
#define IDC_RECOMPSET_TEXT              1253
#define IDC_VIS_TEXT                    1254
#define IDC_CHECK2                      1256
#define IDC_SHOWMOREERRORS              1256
#define IDC_EDIT1                       1257
#define IDC_CLEARMEMORY                 1258
#define IDC_CLEAR_MEMORY                1258
#define IDC_CHECK1                      1259
#define IDC_USEDEBUGGER                 1259
#define IDC_END                         1260
#define IDC_BOOKMARK_VADDR              1261
#define IDC_BOOKMARK_PADDR              1262
#define IDC_START                       1263
#define IDC_ISVIEWER                    1264
#define ID_FILE_OPEN_ROM                40001
#define ID_FILE_ROM_INFO                40002
#define ID_FILE_EXIT                    40005
#define ID_DEBUGGER_MEMORY              40008
#define ID_DEBUGGER_R4300IREGISTERS     40009
#define ID_HELP_ABOUT                   40010
#define ID_DEBUGGER_R4300ICOMMANDS      40018
#define ID_OPTIONS_MAPPINGS_OPENMAPFILE 40019
#define ID_OPTIONS_MAPPINGS_CLOSEMAPFILE 40020
#define ID_OPTIONS_MAPPINGS_AUTOLOADMAPFILE 40021
#define ID_DEBUGGER_SETBREAKPOINT       40026
#define ID_DEBUGGER_SHOWUNHANDLEDMEMORYACCESSES 40035
#define ID_OPTIONS_PROFILING_ON         40059
#define ID_OPTIONS_PROFILING_OFF        40060
#define ID_OPTIONS_PROFILING_LOGINDIVIDUALBLOCKS 40062
#define ID_OPTIONS_PROFILING_RESETSTATS 40063
#define ID_OPTIONS_PROFILING_GENERATELOG 40064
#define ID_OPTIONS_CONFIG_GFX           40073
#define ID_OPTIONS_CONFIG_RSP           40075
#define ID_OPTIONS_CONFIG_CONTROL       40076
#define ID_DEBUGGER_TLBENTRIES          40078
#define ID_CPU_RESET                    40079
#define ID_OPTIONS_CONFIG_AUDIO         40090
#define ID_DEBUGGER_SHOWTLBMISSES       40091
#define ID_DEBUGGER_LOGOPTIONS          40093
#define ID_DEBUGGER_GENERATELOG         40094
#define ID_FILE_STARTEMULATION          40101
#define ID_FILE_ENDEMULATION            40102
#define ID_CPU_PAUSE                    40108
#define ID_CPU_SAVE                     40109
#define ID_CPU_RESTORE                  40110
#define ID_CURRENTSAVE_DEFAULT          40112
#define ID_CURRENTSAVE_1                40114
#define ID_CURRENTSAVE_2                40115
#define ID_CURRENTSAVE_3                40116
#define ID_CURRENTSAVE_4                40117
#define ID_CURRENTSAVE_5                40118
#define ID_CURRENTSAVE_6                40119
#define ID_CURRENTSAVE_7                40120
#define ID_CURRENTSAVE_8                40121
#define ID_CURRENTSAVE_9                40122
#define ID_CURRENTSAVE_10               40203
#define ID_CURRENTSAVE_11               40204
#define ID_CURRENTSAVE_12               40205
#define ID_CURRENTSAVE_13               40206
#define ID_CURRENTSAVE_14               40207
#define ID_CURRENTSAVE_15               40208
#define ID_CURRENTSAVE_16               40209
#define ID_CURRENTSAVE_17               40210
#define ID_CURRENTSAVE_18               40211
#define ID_CURRENTSAVE_19               40212
#define ID_OPTIONS_FULLSCREEN           40123
#define ID_DEBUGGER_SHOWDLISTALISTCOUNT 40124
#define ID_OPTIONS_SETTINGS             40126
#define ID_SYSTEM_GENERATEBITMAP        40127
#define ID_OPTIONS_CHEATS               40128
#define ID_DEBUGGER_SHOWPIFRAMERRORS    40129
#define ID_OPTIONS_SHOWCPUUSAGE         40131
#define ID_DEBUGGER_CALLSTACK           40133
#define ID_CPU_SAVEAS                   40134
#define ID_CPU_LOAD                     40135
#define ID_DEBUGGER_SHOWCOMPMEM         40136
#define ID_FILE_ROMDIRECTORY            40137
#define ID_FILE_REFRESHROMLIST          40138
#define ID_SYSTEM_LIMITFPS              40141
#define ID_HELP_CONTENTS                40142
#define ID_HELP_ABOUTSETTINGFILES       40146
#define ID_SYSTEM_GSBUTTON              40148
#define ID_HELP_GAMEFAQ                 40149
#define ID_OPTIONS_ALWAYSONTOP          40150
#define ID_PLAYGAME                     40152
#define ID_EDITSETTINGS                 40153
#define ID_EDITCHEATS                   40154
#define ID_POPUPMENU_ROMINFORMATION     40155
#define ID_EDIT                         40159
#define ID_POPUP_ADDNEWCHEAT            40161
#define ID_POPUP_EDIT                   40162
#define ID_POPUP_DELETE                 40163
#define ID_HELP_GITHUB                  40164
#define ID_HELP_HOMEPAGE                40165
#define ID_SYSTEM_CHEATSEARCH           40166
#define ID_POPUPMENU_GAMEINFORMATION    40169
#define ID_FILE_GAMEINFORMATION         40170
#define ID_HELP_DISCORD                 40171
#define ID_SHOW_CURSOR                  40172

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         40214
#define _APS_NEXT_CONTROL_VALUE         1265
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
